/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{vue,js,ts,jsx,tsx}'],
  theme: {
    extend: {
      screens: {
        '2xl': { max: '1440px' },
        xl: { max: '1024px' },
        lg: { max: '836px' },
        md: { max: '768px' },
        sm: { max: '500px' },
      },
      colors: {
        main: 'rgba(var(--main))',
        aside: 'rgba(var(--aside))',
        border: 'rgba(var(--border))',
        whiteText: 'rgba(var(--whiteText))',
        blueText: 'rgba(var(--blueText))',
        greenColor: 'rgba(var(--greenColor))',
        lightGreen: 'rgba(var(--lightGreen))',
        hoverGreen: 'rgba(var(--hoverGreen))',
        redColor: 'rgba(var(--redColor))',
        lightRed: 'rgba(var(--lightRed))',
        hoverRed: 'rgba(var(--hoverRed))',
        blueColor: 'rgba(var(--blueColor))',
        lightBlue: 'rgba(var(--lightBlue))',
        hoverBlue: 'rgba(var(--hoverBlue))',
        yellowColor: 'rgba(var(--yellowColor))',
        lightYellow: 'rgba(var(--lightYellow))',
        hoverYellow: 'rgba(var(--hoverYellow))',
        defaultColor: 'rgba(var(--defaultColor))',
        changeText: 'rgba(var(--changeText))',
        mainText: 'rgba(var(--mainText))',
        hoverAside: 'rgba(var(--hoverAside))',
        hover: 'rgba(var(--hover))',
        placeholder: 'rgba(var(--placeholder))',
        blur: 'rgba(var(--blur))',
        cancelBtn: 'rgba(var(--cancelBtn))',
        btnHover: 'rgba(var(--btnHover))',
        btn: 'rgba(var(--btn))',
        searchBg: 'rgba(var(--searchBg))',
        searchBgNotFound: 'rgba(var(--searchBgNotFound))',
        index2: 'rgba(var(--index2))',
        overlayBg: 'rgba(var(--overlayBg))',
        linkbg: 'rgba(var(--linkbg))',
        linkHover: 'rgba(var(--linkHover))',
        editBtn: 'rgba(var(--editBtn))',
        editBtnHover: 'rgba(var(--editBtnHover))',
        loginbg: 'rgba(var(--loginbg))',
        formbg: 'rgba(var(--formbg))',
        modal: 'rgba(var(--modal))',

        // SCROLL
        scrollTrack: 'rgba(var(--scrollTrack))',
        scrollBar: 'rgba(var(--scrollBar))',
        scrollThumb: 'rgba(var(--scrollThumb))',
        scrollHover: 'rgba(var(--scrollHover))',

        mainScrollTrack: 'rgba(var(--mainScrollTrack))',
        mainScrollThumb: 'rgba(var(--mainScrollThumb))',
        mainScrollHover: 'rgba(var(--mainScrollHover))',
        // SCROLL
      },
    },
  },
  plugins: [],
}
